;;; local-test.el --- Local iglab smoke test config -*- lexical-binding: t; -*-

;; Usage:
;;
;;   1. Fill in the values in the "Required local settings" section.
;;   2. Run:
;;
;;        emacs -Q -l local-test.el
;;
;;   3. Use:
;;
;;        M-x iglab-local-test-init-db
;;        M-x iglab-local-test-sync-active
;;        M-x iglab-local-test-render-org
;;        M-x iglab-local-test-dashboard
;;
;; `iglab-local-test-render-org' renders whatever is already in SQLite. Run
;; `iglab-local-test-sync-active' first if you expect real GitLab issues.
;; Sync runs asynchronously and streams progress to the *iglab* buffer.

;;; Required local settings

(setq iglab-local-test-gitlab-host "https://git.iris-view.com")
(setq iglab-local-test-gitlab-token "glpat-lHqTbfCS1-bGN96j3NQqFm86MQp1OjFkCA.01.0y0oxek4e")
(setq iglab-local-test-root-groups '("project"))
(setq iglab-local-test-project-paths '("sdk/issue"))

;;; Project-local paths

(defvar iglab-local-test-directory
  (file-name-directory (or load-file-name buffer-file-name))
  "Directory containing this local test file.")

(defvar iglab-local-test-db-file
  (expand-file-name "local-test-cache.sqlite" iglab-local-test-directory)
  "SQLite database used by the local smoke test.")

(defvar iglab-local-test-org-file
  (expand-file-name "local-test-gitlab-issues.org" iglab-local-test-directory)
  "Org file generated by the local smoke test.")

;;; Load iglab

(add-to-list 'load-path iglab-local-test-directory)
(require 'iglab)

(setq iglab-python-command "python")
(setq iglab-database-file iglab-local-test-db-file)
(setq iglab-org-file iglab-local-test-org-file)
(setq iglab-gitlab-host iglab-local-test-gitlab-host)
(setq iglab-gitlab-token iglab-local-test-gitlab-token)
(setq iglab-root-groups iglab-local-test-root-groups)
(setq iglab-project-paths iglab-local-test-project-paths)

;;; Smoke-test helpers

(defun iglab-local-test-init-db ()
  "Initialize the local smoke-test SQLite database."
  (interactive)
  (iglab-init-db))

(defun iglab-local-test-render-org ()
  "Render the local smoke-test Org file from SQLite."
  (interactive)
  (iglab-render-org)
  (find-file iglab-local-test-org-file))

(defun iglab-local-test-sync-active ()
  "Run active-scope sync through the Emacs wrapper."
  (interactive)
  (iglab-sync "active"))

(defun iglab-local-test-dashboard ()
  "Open the local smoke-test dashboard."
  (interactive)
  (iglab-dashboard))

(defun iglab-local-test-show-config ()
  "Show the local smoke-test configuration."
  (interactive)
  (message "host=%s groups=%S projects=%S db=%s org=%s"
           iglab-gitlab-host
           iglab-root-groups
           iglab-project-paths
           iglab-database-file
           iglab-org-file))

(message "iglab local test loaded. Start with M-x iglab-local-test-init-db")

;;; local-test.el ends here
